apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: default
spec:
  replicas: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 250m
      memory: 512Mi