---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pgadmin-secret
  namespace: postgresql
spec:
  encryptedData:
    pgadmin-password: AgBxfWw+eEadFMvVrg+FJY8hJn11ne+UzUiVqu+2UNSiYhjGc0XFCj3waAmOMaBbwSbVTarBKRnxqmCtgyz7UNC/h1tU1zztlbAIKDk0jQW+0ul0pj/HicluJVyK4qe7oukdgXdDi7Rwa1K4CuQ6rUrS5uKU7BSZZwGgP2w/oE4WvCgo2qVvIomIa5Q9Pk/oEwLZImvCL59RI6TdY1le6itLYY6uvXvXUQ/nTnQoYFWNC1FGiGLs8aZ3TuRHrvO+zrCWua/xLTRL7zHksEPzZO3Brgwcc2SBR2XXY+bWBLIxKpGGTPoy5QpPBOWZdnHbj2oS+03zrpjf9SawJZiMWaLWrwhxzTa6kpPzqy7bmCx7Xg/uV3T3LQjai5smj0GOSDN5Io4SV461fpICh17gF+tP5NX931cRnKsId0gIE8pD23mDWpK92eO/QxMoxXSGUYkKsuCZDNU4jq03Wj30qR2jFB/qqHlrt//wUHa2i0BhlRYnRsh4zsNd5ba8wjWGXnSWnXMAXK8tNAkGlrIgRMnGuwH7M9QpHOIWopX68G9f98QV/0h4W97i4QE4/Spba7wCuD3+yTukTsvPgWTZcddOwd5rnIPEsLIzlw/Rrvb1PbCFwAkE1Pg2X+eWfPX9k44s3/TzHMxnuItQeA1JH5Eqb85+XXfm23grx4bbRL542fMVRbuPNXKKvernUyo7DpIfrjUAnX3ijg==
  template:
    metadata:
      creationTimestamp: null
      name: pgadmin-secret
      namespace: postgresql
