apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "PostgreSQL DB",
          "Group": "Servers",
          "Port": 5432,
          "Username": "admin",
          "Host": "postgres",
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres"
        }
      }
    }
  PGADMIN_DEFAULT_EMAIL: "a.meowalien@gmail.com"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgadmin
spec:
  serviceName: pgadmin-service
  podManagementPolicy: Parallel
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-pgadmin
          image: busybox
          command: ['sh', '-c', 'mkdir -p /var/lib/pgadmin/sessions; mkdir -p /var/lib/pgadmin/storage; chown -R 5050:5050 /var/lib/pgadmin']
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:8.10
          imagePullPolicy: IfNotPresent
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: pgadmin-config
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: pgadmin-password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: pgadmin-config
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin
      volumes:
        - name: pgadmin-config
          configMap:
            name: pgadmin-config
  volumeClaimTemplates:
    - metadata:
        name: pgadmin-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
---

apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: pgadmin
