---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: postgresql
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBEg1LfpCflOGoj00BBcRC+HQZGgr7O58unAw/pa1QK7rO/dwH9pPqheijP+vP4H71IZuH4sK5297c8DfWg5dECMcoohE4UBqM6MomIutFtLU8mRaxHER2wPq46c5uKJm5Gk453mAFA7NJzbO6Ixbs+VvAe4RTnfbeGUqhUb1cd4kfjnES+rMC1Zn4j2t4WMych6PhySVPBBdtooudCynupmXPGZlrVGPQQJOSqwcRx8E5NmE07Gj+hniQ9pzqPd5TKdACQgi2yRcpxtDMRROVYBbsRenXDQtZupY1yF5UmS7r8PfvtrX0AB80xmF77dN88dfMCSXldoL3ADuS0SwAfcz9o1M/phD1kUU4hJrk3dtPMHyh1uR1cX22VrPBsyhgzi2KXt06nKt6Nj2Ke+hS5Ct+YOumuLDeFW0PSQt2q5PJCAKuiyITMl2g3Tl9Ym7uH4aRfoDLPXqzk+vjjSRt5Rcw6Sv5kaHJPmRZznzifUqb3bPz6QX761Kbi/cOLKrV+kmqsJRNhoBHVlsLvtjzpAZv5tmodjWjZe6Kkn1iSdNoGPTmvziXNOXEdmZfhrxBbPON9ONFT+BBWuufzS4zkpMCAdp9Zs/SNs5GnuELuMUCGuWmSIC/QPM0ERpqhAGDMWGmkUotiWNCiSB/1y9G1CaQ4uSUr1HUjpRe1K6CYajVMfbQgCzj8dTmTwxK0uBN3FDCf77f4kw==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: postgresql
