---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: postgresql
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBQ6W7t7hn+EBN/EeRyEBLza+j1MuJsYvDSN7MxFx9teXSkGFKQ+dh380lLPXlFnG0uygjdE3xB7PjVI1ZIdTKHfr9OkvXr9zS3zd13w1dUfZdWa0hP0bCSSq1CBOqUCA8aNLdiqsCKELm5NaxraKaw9AwFFOFK9jBwsUFCGoLKpFaWpiaztMJaC74oiWuAwoFpkE3dNVgDhmWYdiKV7ivW5Uig2IxwkAUz9g+VBNOZ4jDYCcacCNQkuTCt578cfK1ENGB9QBp7O84942z2gdY7svpV3yL4JTqrDugdKODj3pSHmZWfZzXTJLq7Ex2WBM+yECPVy4N7/lpb4+1+OtqwfbDx6AZclviiVvdhAmubHlNo0ADYZoTHoXfJa1J9XCI+E1sbX3GnWZx+9a2oECWuYXHnBjgamhAfbHlYJRx9KHfb+eK/2850itu7w5irQT5JyH8nm7vu6bkUyWGbP+qGnl0pVoLyR2xRQQcP1M+nYR52n+EkWFZCrIkHOWAfMqK1aaxqawRxJPOMOosHGB5FcBwgFN//eNjvMJCYAhSJw94HVgFNV8G+KcjBvBBq3PzyVMA8V2V9+xMS1sRNb1ZNY2n9FKLBA0QNCV1PpRp7nnKxvR1S65W9xbqHXYXMCmSyvkBt9oqvILyDAxSnwI05gx9qc4WdfWtO2hfZbE9s5aFOp9VstcLl2DSLafQKtcAkA0uTlBok0Q==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: postgresql
