---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: postgresql
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBJ8kQyyQmadk/c6Tt+4bR4yaI8Lrm9pCf+OLVROQPYYJgZoLnCYneFkNT0mWyOr7FMGsi5cAR1j97KyBwYTAhi1CJn2q+VOwAY4LWKbdNK5MGXQNm4PJnxv1U/O1LimSD8DRVcJL3LokSA2agYGOlnQT/TRN+K2rnlFbXy6g1XYI7QlFNiNFICF2So5+DFO0wGdZRHrIDeB1OWt6JcrnfhBPgK3BIi/ZriGu5qZE+MOyuWP0XxWxp0+txo6nn+B4krZCaGJx0uqD1wYong8l9cPPhucFagvNAGxoXf0KIKm6Y+npK4UDIjdR4aNC3bKI0vQfwUiQoHu+kZPo5wxjfDh9Fcft8M9H40zN05ZRnFgi9vy5epQX5EMZlKCSayRwul1as44fbhjYfoTrg9JjgWpibF3VYuNkuLTCECYbtvYFNBLsKgy7piCRB5po5PKUYJ1JLlfxSe2MH2dFoqQmY+jmUU0N0hIL3x0zGwYpith43QkmTYH6/OaTTOMlyMOiBdQtuqwElu3tVQPQyBudM44k+t0xHL+9JssrfiEs2+P7806ctnloixkL11+BB7wfbN6by/ZbnLiyYJzgGxVKIYzzskAvVBGZ0AHSwSjGXat6RpHXkSXzO+ZmXHLwDWgW6VH0as8ftifzxg1Edey82YCygXvT4NzgD/VRcokq++em7u52bnXIhAuWYM9+G6UEi4jNbTJaQu/g==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: postgresql
