apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_USER: "admin"  # Specify the default username for PostgreSQL.
  PGDATA: "/var/lib/postgresql/data/pgdata"  # Specify the data directory for PostgreSQL.
  POSTGRES_PASSWORD: "password"  # Specify the default password for PostgreSQL.
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgressql
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgressql
  template:
    metadata:
      labels:
        app: postgressql
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          resources:
            requests:
              cpu: "10m"
              memory: "150Mi"
#          env:
#            - name: POSTGRES_PASSWORD
#              valueFrom:
#                configMapKeyRef:
#                  name: postgres-config
#                  key: POSTGRES_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-secret
#                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
        storageClassName: standard

---

apiVersion: v1
kind: Service
metadata:
  name: postgressql-service
  labels:
    app: postgressql
spec:
  ports:
    - port: 5432
  selector:
    app: postgressql
