apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:meowalien/homepage-cluster-config.git
    targetRevision: HEAD
    path: homepage
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:meowalien/homepage-cluster-config.git
    targetRevision: HEAD
    path: postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:meowalien/homepage-cluster-config.git
    targetRevision: HEAD
    path: sealed-secrets
    helm:
      values: |
        fullnameOverride: sealed-secrets-controller
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:meowalien/homepage-cluster-config.git
    targetRevision: HEAD
    path: mongodb-operator
    helm:
      values: |
        operator:
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              memory: "512Mi"
          watchNamespace: "mongodb-cluster"
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-cluster
  namespace: argocd
spec:
  project: default
  source:
      repoURL: git@github.com:meowalien/homepage-cluster-config.git
      targetRevision: HEAD
      path: mongodb-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb-cluster
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-express
  namespace: argocd
spec:
  project: default
  source:
      repoURL: git@github.com:meowalien/homepage-cluster-config.git
      targetRevision: HEAD
      path: mongo-express
  destination:
    server: https://kubernetes.default.svc
    namespace: mongo-express
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3
