apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:1.0.2-20
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "admin"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "password"
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "root"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-express-secret
              key: ME_CONFIG_MONGODB_ADMINPASSWORD
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongodb-cluster-0.mongodb-cluster-svc.mongodb-cluster.svc.cluster.local,mongodb-cluster-1.mongodb-cluster-svc.mongodb-cluster.svc.cluster.local,mongodb-cluster-2.mongodb-cluster-svc.mongodb-cluster.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 8081
