---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: public-key
  namespace: homepage
spec:
  encryptedData:
    public_key.pem: AgAy8p7Fr2trOpoOKqEB6CPBYGRVhUVn8k2c6L6/AhTkLXnMqItU8DGj5B3vgqZu3Le57iU0mcwiupdKnTuizLE+qDjQ/Of08Yv/DzXb8SDE2sjWGPq1XBEBe7Wn52IB/bzJT9/UApeUXcxV69B0Aie9tX1sh9G6N68SRGwydZmpqUUC0fwC2m+sXfmcqG1NzTE/lJH0YZRuy+v+KioEeukvDNHn4j08RGjNIzLnmVVUojeqPxO55dIZYUsbC0DK9OlS6TsJ69TjarLj2vwEEtoHuOo7iItpzA86I4r36Q8iXzfYXV1dyr2vYWX8YwuQy4MbXZsupZY+iE3vYJNLKYS15iYA7WvZCrakO64NiJ39DOjN57PjjyAImxc6fyWGAlqK37ftqkr5yWbbC+tWacxx5CvPIW420+1nOgCO5Rj+4gHJMDhLJ005PL9pjCkX81TJzYtnluGnZlcZ9z5chxeH2xuybKGI5b98bkWdW4uVZ0HZ9BOlfqD6IQ8mkipfFtE8OEDFlNJwGCp7Wo9z0pJQp42NYEWpMRSfn9HkB5oIcojqOQsWnN9PxFWuKjSIjfrnyi+P3n3QUe6CBzeAa85GPWwmHlAQ2QPrWNN+F1JnsPPdkIyOvwiyGy/ispd/2kcyHS6FwtaAQf37r+u2KZJJfTQ1XitnQdEFCRyN1j6T1n0yOhHvDl6kYiPISaLFnYHZhtxe9BhXg09ai0e858RBFXFKN8kVi1puTcTfVVehI2tpRmwpGUcVkJxJ4umkc8fH09xeTitiNZLw/xRYGOyk11eK5sSbFxHePS6VpSDHHvq24tei6z6P7GnnWAIMT7N52StcKjBI4BBlFiKF17ppDE1X8jn7vZpcKIIVKePSdyFBkm4M6zGRL5tBiFtkyqCVOc5KjVbeBM+DJCjH3U21wiEvUFHEJtXSAXa0vzepReWPCBOa7gVTxnhB8XRYAwODcFGPdkgGnUUXQuBm8ZLAYCpFzBgOVMGeQAn0Ui9X5yD32HDf98GDflPFt2PtXd5f4JLxitj9E4dWtdgnQk3SfS7T4bHP2qW7qo5qgj/vncDg3p/NtnAqxBMnIl011RUCdK0COfAvsDKy/ZjKjVaatcW25u4vO4JaWuDHeGNI9vu1w7p1uSPslNpWxxswf9ma5LxLS/4oRnlILMJaUXk99bLGuBEFeNfn2nChSACadB6K7C4C5whcxp0P+KZ9TanOYrOezF/AGs+1wPEtiYksqC3W9jUDQ8JMch5gcGXstNYHpbu/R2w2KN4AwHaNf0P9ymv6bo898SYwjn9wtsInNvNa
  template:
    metadata:
      creationTimestamp: null
      name: public-key
      namespace: homepage
