---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: public-key
  namespace: homepage
spec:
  encryptedData:
    public_key.pem: AgAC7HXHOJ7zu75AGWkI2ZEBEJoc3vv1N0E1PYc7SjhmknEBXdE7E08WTLHQgZjjzjq74H3pL4zL9p7+XZKYoZm9XLyLxLhUogYIIywrefexw6SY7bTm8jwp9FCzr1jnAVSt/4mTaVCdSfbK1DfhCYNOaB3Z+/nn9t8wHuLTPfbGTOOkEqCp4PwJD7y5U0DKqxGSjBF+YbNv7gkHJNM53YN2zQjEcWylH1oAgIR/V8HidHjcVAqLdkoCHuxkO8yweTbQSFJdOGn42uv1mg5/hvfwsjeHhntbGA0IWYGMS7KwicZz6PSeySIkWPv8c41HB1HNt5xKW0zOseieiojwKOVE7ChLBpytbFtnMFUBgyme0HvIhUamqHquKCuGZVCI3+GLWLJ3eNVlm4/7DwI3bL6R9tBfsmntXiIBwiDgTM41Zr9lIM1NeerCOqYH0Y/J1aJ6FOePxqnij2gVKnqSKr78T3yJhksdKqmsA9QYHlP3psKQxCXigPiJqjveiTnnIUcC4YZ8RDKyvx1ac+V/n9OEo/Q2GT9jP8BS3/d9ApVeJlGzYuzEg+mVFQOn5qmud7xghd4f7PQklXdOZqkUafxCUjzowIFHu38RB8s+LxztGxdsjOJB9VWOvcNYI8i0zvYBm0zsMfYblrDfQJ7bK/X7B6z5pVneYFLbJr5xVNNnsjyoAWal06ZArRdq496yYpWZtkO+prSHmnj3YBlPGZ/TrSgoP4kQ7NyaYCvTTQnpDz84BEBE9NL6/ZxnPOishBAJFn75TM8SKPe9KIm5UIZ9XA0R2s9ar0DVQxpj7lfwcsRlOzZEZ3xR0lBk7+cWKqL4+6im5nwVRQJABIrlzcn/grtk5uSCIsmy7XVIYWx7HJRKBHAIl6oYQFch9cLQdKVF+n78PWP+0wVj9JCzy33eNxj97TaSwIVHpm8caRT/OsGrzkC3uYcKTFIs14SrrzHcshiQYR5fIeLvx/CuiXjxODQMIps763xaRZgcSP3K2tWAlg4xlOdFbSIVZgz3GNLNCQpYmkxsRj0doUabqZn/Z8ioSt/ovTUsNuiVCr4kLieorYouqzsV4bbIw6JKo/Z54BPqKVo9rLx7sRw8g1dBOPWSV+V8FKFRRKb/mrGiXmB+ogAL/24ernnsU01afurYplyrJJA1/9glsZOQUoQeBdNCG1f90l+YFNY4xwe92TECr16xZQmowK9Bz5GCgVBZpQVMSalLkTmeGgVA50fAp1IWDxn9XgjUt8bXYrtN/LMSZ0ziAo2keeAMA9LrpW19V1OAQItc3jmVIPdW1UsGXW+I
  template:
    metadata:
      creationTimestamp: null
      name: public-key
      namespace: homepage
